language: rust
rust:
- nightly
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJE4R64EUVXUXAV7
  secret_access_key:
    secure: UlyvRsBkyZoa7O4QKMBaLk89W+DYcbQwgvCcB4NpTtTiZnDBw/wL6TVBv1X0yHBFWhHxAoC0FgESpKSa58l+y2/Zhzyg17NecIn7je17ukAoDzllhFFJkgLFiIxj0x9yzl43t1q5SapSV29RHfJMqcsnfsIc3z1rnMTfXdvW3XJgFa+Jqji+KLn1l2r7iJlQyaXash4YIY7A0ywWRPp3fW0Sf37vnj0nrAwgi3UaKXxAkOVwtg/cHUdxlkTHvnASKZ/5i3P0n3Q8qgjlIo7l7vUioSfJbtIp1kcnd2QYmVhTudZ1WchY5uwfS+xvqB1vu6SZv9cqhr3ZKqWuRNt5qwXi0BY/kcJ/kCrJiytuKA8j0cnbByeQgkELbyznON6poKg1iyMB4KaT3of87o7jWYANtLj+vv0b8GwqUmTUCIRmu8JEm83b090Y5IWxOdAgyWbchHJGTZUWVsWT72RxR/x+bCWzF2fWdwKl+I55xn0eyZnIwAYQej21LgnurtgKJQXfkdQUqaF+JEUCY6tXIMObyOrbRIbTBzrXa1/DfaElNnVrTeTUar4lUFZDVN/Pk6l4efxdH/TfbaEiSZHEFjJqlzzZ8l0BsXwF07sa7+j38rSbiMsYXIav+UPiClWSZiym78/6+QWGFyc4qO2wjYyVpft83P29A2LanGXZm5c=
  region: us-east-1
  app: hangry-river-horse
  env: Sample-env-1
  bucket_name: elasticbeanstalk-us-east-1-706915058092
  on:
    repo: excaliburHisSheath/hangry-river-horse
    branch: aws-codedeploy
