language: rust
rust:
- nightly
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJE4R64EUVXUXAV7
  secret_access_key:
    secure: tSM2vi2htoL39v/l1V5LeeVCg/CIKtBWhiNkFJOY+Fsp1vAeADN3fAm+xCjPn4PC/119XdbVD4BZYOASZco1ZGRgYX34h4GG+8jqvoS0We4E7s0sORqz8hhSiI5CaUQa5xLiEVLksCJlWsZANDEEiymO8vhIffjKiBuWkt+TpQbK6Tg0uwfVd1IHjUps0C22iAYeXkiW5vqulGrsUdrB1AjjMyEX6h0BclsMy0jgkkJ7KN+RuSBEX+/T89H9GLrbaVWJ7s+OV22BuKxaQNuHTVql6uejjsMIbhQjh9zeLfGWbxQs838Qm8hHeLvpMMA4rW5wBlZ2o4j0Pmgj3C1ktlh+LjRkbMSghgTKSm6yxU1whsKohPLx9mxTcfvZ5zrBHFgZ3iz20qJO8bFxJzWwgvdJvRAaTLmrFzZw7FrIRxeWzaIEKe0zAhEN9PYav06gdK+7579+94SUe6Gr9LYwp/5ttqzKQYpma96PQpAMaUWtSd9BuIeyNltgRiY3zL3VZ4K/MPQc/tI57RFBA+gulTjAJJg2qONywVLVVmCXAIMGhHOQGsaGWJVxBKevQDAsNTNqtAkmvqlEJL5CU+YhfjEpawFUzecNgCJ5o9LQox0dG+QXC3Qs+frj2EPWh8Z3/juSEfSRaS9XYhC3fPSFvaWB9hygXb/XzZM94XzE64o=
  region: us-east-1
  app: hangry-river-horse
  env: Sample-env-1
  bucket_name: elasticbeanstalk-us-east-1-706915058092
  on:
    repo: excaliburHisSheath/hangry-river-horse
    branch: aws-codedeploy
